language: bash
sudo: required

services:
- docker

before_install:
- docker pull konh/unity_build_image:latest
jobs:
  include:
  - stage: install
    script: "docker run -e UNITY_USERNAME -e UNITY_PASSWORD konh/unity_build_image:latest /bin/bash -c ~/docker_install.sh"
  - stage: build
    script: "docker run -e UNITY_USERNAME -e UNITY_PASSWORD -e UNITY_ULF konh/unity_build_image:latest /bin/bash -c ~/docker_build.sh"
  - stage: upload
    script: "docker run -e BUTLER_API_KEY -e ITCH_TARGET konh/unity_build_image:latest /bin/bash -c ~/docker_upload.sh"
